apiVersion: v1
kind: Service
metadata:
  name: todo-nodeport-service
spec:
  selector:
    app: todolist
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30000
